name: Build & Push

on:
  push:
    branches: ["test"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: olivaresiago/daw-web:latest

      - name: Ejecutar el contenedor
        run: |
          docker stop web-container || true
          docker rm web-container || true
          docker run -d --name web-container -p 8888:80 olivaresiago/daw-web:latest
